Support for non-working copy repositories
Sometimes we just want a repository on a hard drive somewhere but we don't want
to duplicate every file by also having a working copy sitting around. In this
case, to help prevent someone from thinking that there is nothing in a specific
directory, we don't want to use the "." prefix for the layout and objects
directories.

diff --git a/bt-commit b/bt-commit
--- a/bt-commit
+++ b/bt-commit
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+# are we in a normal BlobTracker repository
+if [ -d .bt_objects -a -d .bt_layout ]; then
+    true
+# or a non-working directory BlobTracker repository
+elif [ -d bt_objects -a -d bt_layout ]; then
+    echo "You can't do a commit on non-working directory repositories."
+    exit 1
+else
+    echo "This is not a BlobTracker repository."
+    exit 1
+fi
+
 recursively_add() {
     for x in $1/*; do
         if [ $x == "$1/*" ]; then continue; fi
@@ -37,17 +49,6 @@ recursively_remove() {
         fi
     done
 }
-
-# determine if we should even be looking at this directory
-if [ ! -d .bt_objects ]; then
-    echo "This is not a BlobTracker repository."
-    exit 1
-fi
-
-# create the .bt_layout directory, if it doesn't already exist
-if [ ! -d .bt_layout ]; then
-    mkdir .bt_layout
-fi
 
 # recursively add new or modified files to the layout
 recursively_add .
diff --git a/bt-reset b/bt-reset
--- a/bt-reset
+++ b/bt-reset
@@ -3,6 +3,18 @@
 # rsync --size-only --progress
 # git pull
 
+# are we in a normal BlobTracker repository
+if [ -d .bt_objects -a -d .bt_layout ]; then
+    true
+# or a non-working directory BlobTracker repository
+elif [ -d bt_objects -a -d bt_layout ]; then
+    echo "You can't do a reset on non-working directory repositories."
+    exit 1
+else
+    echo "This is not a BlobTracker repository."
+    exit 1
+fi
+
 handle_dir() {
     for x in $1/*; do
         if [ $x == "$1/*" ]; then continue; fi
@@ -23,12 +35,6 @@ handle_dir() {
         fi
     done
 }
-
-# check that this is a valid directory
-if [ ! -d .bt_objects ]; then
-    echo "This is not a BlobTracker repository."
-    exit 1
-fi
 
 cd .bt_layout
 handle_dir .
